Adds calculations for computations to be done using DPR
pooltogether/v4-utils-js pull request #80
Opened 2022-11-08 16:05 UTC by dylandesrosier

Adds calculations for computations to be done using DPR rather than TVL. 

- Added `PrizeTierV2` data type
- `calculateCardinality` was fixed. I had to update some old tests since `computeCardinality` was off by 1. 
- Changed a few parameters from `BigNumber` to `BigNumberish`. It's backwards compatible and supports more incoming types since we use it in a few different locations.
- Added some comments & renamed some parameters to be more explicit
- Exposed `calculateNumberOfPrizesPerTier` and `calculateTotalSupplyOfPicks`

2022-11-08 21:08 UTC, PierrickGT requested changes

2022-11-09 14:59 UTC, dylandesrosier commented on src/calculate/calculateCardinality.ts
> +        );
That makes sense to me. I copied starting at 3 from [here](https://github.com/pooltogether/v4-simulator/blob/main/src/lib/computeCardinality.ts).

2022-11-09 15:10 UTC, dylandesrosier commented on src/compute/computePrizeDistributionWithDpr.ts
> +        endTimestampOffset: 0,
`prizeTier.endTimestampOffset` doesn't exist. This is old code from [here](https://github.com/pooltogether/v4-utils-js/blob/6079be015be46e84a4a7abb397eba6f5ebe7ea97/src/compute/computePrizeDistributionFromTicketAverageTotalSupplies.ts#L81) adapted to support DPR, I assumed that was correct.

2022-11-09 15:24 UTC, dylandesrosier commented on src/compute/computePrizeDistributionWithDpr.ts
> +        endTimestampOffset: 0,
[Looking deeper](https://github.com/search?p=1&q=org%3Apooltogether+computePrizeDistributionFromTicketAverageTotalSupplies&type=Code), I don't see any use of [that function](https://github.com/pooltogether/v4-utils-js/blob/6079be015be46e84a4a7abb397eba6f5ebe7ea97/src/compute/computePrizeDistributionFromTicketAverageTotalSupplies.ts#L12) in our repos 🤔, so it probably is incorrect.

2022-11-10 21:10 UTC, PierrickGT approved these changes

2022-11-10 21:12 UTC, merged